### ISSUE TITLE
Memory Leak v0.0.10

### ISSUE THREAD

**Issue by EpicGazel** [NickMesser/Mystical-Index#1]
[crash-2022-10-02_22.33.34-server.txt](https://github.com/NickMesser/Mystical-Index/files/9694305/crash-2022-10-02_22.33.34-server.txt)
Version: 1.18.2-0.0.10.jar
Modpack: Sky Fabrication 3
JVM args: -Xmx6g -Xms6g -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

After playing for a session long enough (~30mins), a crash happens related to memory and Mystical Index. I am using the magnetism book and it appears related. I've only added apples and scaffolding to the book of magnetism's list. A crash log is attached.

**Comment by NickMesser** [comment]
@EpicGazel I appreciate the report. I will see if I can push a fix for this. I was still kinda new to fabric when I made this mod so I am sure some improvements could be made =D

**Comment by NickMesser** [comment]
Found the issue. I was adding items to a list under filters before clearing previous filters so VERY quickly I was trying to filter millions of items. Will be fixed in my next release.
