### ISSUE TITLE
[Bug]: Crash when trying to insert items into a full book (via hopper on a library) v1.19.4-0.5.1

### ISSUE THREAD

**Issue by Mowmaster** [NickMesser/Mystical-Index#2]
[crash-2023-06-08_11.37.51-server.txt](https://github.com/NickMesser/Mystical-Index/files/11691015/crash-2023-06-08_11.37.51-server.txt)
Was just messing around to see what all the mod had in it so far,

SETUP:
Hopper on top of a library with oak logs in it, opened library gui and inserted a storage book, set to oak logs, with 640 logs in it(default max storage I'm guessing) after closing the gui i lagged out and the game crashed (in single player, player in creative mode)

Also noticed before this happened, if you had a library and a hopper on top transferring logs down, it wouldnt work untill the storage book was inserted, HOWEVER if the book was removed, the logs would continue to be inserted, (and seemingly voided as they didnt drop from the library once broken afterwards) im guessing updating the library block on book insert/removal would solve this though.

**Comment by NickMesser** [comment]
Fixed in recent update #3 with update 1.20.1.
